name: dagger build
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Dagger pipeline
        run: cd dagger && go run main.go
